hosts:
  - name: "ssh machine1"
    address: "10.0.4.12"
    port: 22
    user: "test"
    private_key: "/home/dev/.ssh/id_ed25519"

  - name: "ssh machine2"
    address: "10.0.4.13"
    port: 2222
    user: "test"
    private_key: "/home/dev/.ssh/id_ed25519"
    retry_ssh: "3s"
    retry_ssh_count: 3
